### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by sophieforrest** [tyrossel/MarkdownTable.nvim#1]
Hello! I came across this project not long ago, and I'm interested in forking it and making some modifications. I noticed that there isn't any license though, which means I can't do that.

I was wondering if you'd be open to adding a license to this project?

**Comment by tyrossel** [comment]
Hello ! 

Thank you for reaching out. I'm sorry I noticed your message only now.

I added the MIT license to this project. Hope it helps you !

For the record, I don't intend to work on it further, as I currently use Obsidian for taking notes and creating tables. Still use neovim to code though.
